window.SpendTimeChinese = {
  "START": "开始游戏",
  "CONTINUE": "继续游戏",
  "LEVELS": "关卡",
  "SETTINGS": "设置",
  "LANGUAGE": "语言",
  "LANGUAGE: ENGLISH": "语言：英语",
  "LANGUAGE: RUSSIAN": "语言：俄语",
  "LANGUAGE: CHINESE": "语言：简体中文",
  "ENGLISH": "ENGLISH",
  "RUSSIAN": "РУССКИЙ",
  "CHINESE": "简体中文",
  "English is selected.": "已选择英语。",
  "Russian is selected.": "已选择俄语。",
  "Chinese is selected.": "已选择简体中文。",
  "Choose your language.": "请选择游戏语言。",
  "SOUND": "音效",
  "MUSIC": "音乐",
  "CURVED SCREEN": "曲面屏幕",
  "VIBRATION": "振动",
  "ON": "开",
  "OFF": "关",
  "VOLUME": "音量",
  "SOFT GLASS / SCANLINES": "柔和曲面 / 扫描线",
  "Your office is saved on this device.": "办公室进度保存在此设备上。",
  "NEW OFFICE": "新建办公室",
  "YOUR FIRST DAY": "上班第一天",
  "CHOOSE YOUR BOSS": "选择老板形象",
  "NAME YOUR OFFICE": "为办公室起个名字",
  "Office name": "办公室名称",
  "OPEN COMPANY": "开办公司",
  "Your first week is covered. Rent is 50 coins every seven days.": "首周免租。之后每七天支付50金币租金。",
  "MY OFFICE": "我的办公室",
  "RENT: PAID": "租金已付",
  "NEXT": "下次租金",
  "YOU": "你",
  "TEAM": "同事",
  "TEAM 02": "同事2",
  "HIRE": "招聘",
  "FIRST HIRE": "首位同事",
  "DESK": "办公桌",
  "TABLE": "会议桌",
  "MEETING": "会议",
  "OFFICE PLAN": "办公室规划",
  "ROOM TO GROW": "发展空间",
  "FIRST HIRE / AFTER LEVEL 15": "首位同事 / 通关第15关后",
  "ROOM OPEN": "房间已开放",
  "TEAM ROOM": "团队办公室",
  "MEETING ROOM": "会议室",
  "FIRST WORKPLACE": "首个工位",
  "Another colleague and a workstation.": "再添一位同事和一个工位。",
  "A meeting table and guest chairs.": "一张会议桌，几把来宾椅。",
  "OPEN A ROOM. MAKE IT YOURS.": "解锁房间，打造你的空间。",
  "BACK TO OFFICE": "返回办公室",
  "BACK TO LEVELS": "返回关卡",
  "BACK TO SHOP": "返回商店",
  "SHOP": "商店",
  "TASKS": "任务",
  "DAILY GIFT": "每日礼物",
  "INBOX": "邮箱",
  "OFFICE SHOP": "办公室商店",
  "SCROLL TO SEE ALL": "下滑查看更多",
  "DECOR": "家具",
  "WALLS": "墙面",
  "FLOORS": "地面",
  "BOOSTER PACKS": "道具包",
  "IN USE": "使用中",
  "USE / FREE": "免费使用",
  "USE": "使用",
  "OWNED": "已购买",
  "HIRED": "已入职",
  "HIRE / FREE": "免费招聘",
  "YOUR TARGETS": "关卡目标",
  "LET'S GO": "出发",
  "NEXT LEVEL": "下一关",
  "MOVES": "步数",
  "COMPLETE EVERY TARGET": "完成所有目标",
  "Complete every target. New office supplies arrive every ten tasks.": "完成所有目标。每十关会出现新的办公用品。",
  "Swap the two marked items. Collect three reports.": "交换两个标记物品，消除三个报告。",
  "Match four reports to make an Express Mail.": "消除四个报告，生成一个快递信封。",
  "Tap the envelope. It clears a whole row.": "点击信封，消除整行物品。",
  "Tap the envelope to clear its row.": "点击信封，消除所在行。",
  "Move the lower folder onto the one above.": "将下方文件夹移到上方文件夹上。",
  "Move the lower folder onto the upper one.": "将下方文件夹移到上方文件夹上。",
  "Tap one item to remove it.": "点击一个物品，将它消除。",
  "Tap the crossing point. Clear a row AND column.": "选择一格，同时消除所在行和列。",
  "Tap BOSS to clear its row and column.": "点击BOSS杯，消除所在行和列。",
  "Stack two loose folders. Match three stacks.": "合并两个文件夹，再消除三叠文件。",
  "Match beside a box twice to open it.": "在箱子旁消除两次，即可打开箱子。",
  "Make matches beside the box to open it.": "在箱子旁进行消除，打开箱子。",
  "Clear below the USB drives. Deliver them to the bottom arrows.": "消除U盘下方物品，将U盘送到底部箭头处。",
  "Clear under the drive. Deliver it to the arrows.": "清空U盘下方，将它送到箭头处。",
  "Swap the marked items. Match three calendars.": "交换标记物品，消除三个日历。",
  "One task done. One step closer to your own office.": "又完成一项任务，离梦想办公室更近一步。",
  "+2 BOSS BOOSTERS": "+2个BOSS杯道具",
  "TRY AGAIN": "再试一次",
  "Even printers need a second try. Your office is safe.": "打印机也有重试的时候。你的办公室还在。",
  "THE DAILY TYPING BREAK": "每日打字小挑战",
  "Type five words in 30 seconds. Earn one coffee buff.": "30秒内输入五个词，赢取一杯咖啡。",
  "PRACTICE": "练习",
  "TIME": "时间",
  "WORDS": "词数",
  "Type the word": "输入这个词",
  "ENTER": "确认",
  "SEND": "发送",
  "INBOX RUSH": "邮件速递",
  "Type the word, then press Enter.": "输入词语，确认选字后点击发送。",
  "Five correct words earns the daily coffee. Try again!": "正确输入五个词即可获得每日咖啡。再试试！",
  "Coffee earned! +3 moves on a level of your choice.": "获得咖啡！可为任意一关增加3步。",
  "Practice complete. Today's reward is already claimed.": "练习完成。今日奖励已领取。",
  "NEW OFFICE SUPPLY": "新办公用品",
  "NEW IN THE SHOP": "商店上新",
  "NOW AVAILABLE FOR COINS": "现可使用金币购买",
  "MORE NEW ITEMS": "更多新品",
  "VISIT SHOP": "前往商店",
  "THE BOSS MUG": "BOSS老板杯",
  "A ONE-TIME PRACTICE": "一次性教学",
  "Row and column cleared! Finish this level to earn TWO BOSS boosters.": "整行和整列已消除！通关即可获得两个BOSS杯道具。",
  "Tap BOSS. It clears its entire row and column. BOSS will not spawn in levels.": "点击BOSS杯，消除整行和整列。它不会在后续关卡中自动出现。",
  "YOUR FIRST COLLEAGUE": "你的首位同事",
  "YOUR SECOND COLLEAGUE": "你的第二位同事",
  "A desk is ready. Hire your colleague for free and they will get to work.": "工位已就绪。免费招聘同事，让他们开始工作吧。",
  "LATER": "稍后",
  "FRESH COFFEE": "来杯咖啡",
  "Use one coffee for three extra moves this level?": "使用一杯咖啡，为本关增加3步？",
  "USE COFFEE": "使用咖啡",
  "SAVE IT FOR LATER": "留到以后",
  "THE TASK BOARD": "任务看板",
  "Paid packs will be added later. No payments are enabled in this prototype.": "付费道具包将于日后推出。当前版本尚未开放支付。",
  "A FRESH START?": "重新开始？",
  "This replaces your office, coins and progress.": "这将重置你的办公室、金币和进度。",
  "START NEW OFFICE": "新建办公室",
  "KEEP MY OFFICE": "保留办公室",
  "PAUSED": "已暂停",
  "Take your time. The reports can wait.": "休息一下，报告可以等等。",
  "LEAVE LEVEL": "退出关卡",
  "LET'S TRY": "试试看",
  "RENT NOTICE": "租金账单",
  "50 COINS / EVERY 7 DAYS": "每7天 / 50金币",
  "NEW BILLS": "新增账单",
  "OLD DEBT": "未付欠款",
  "TOTAL DUE": "应付总额",
  "COINS AVAILABLE": "可用金币",
  "NEXT RENT": "下次租金",
  "PAY 50 COINS": "支付50金币",
  "One more unpaid bill will close your office.": "再拖欠一张账单，办公室就会关闭。",
  "Leaving this rent unpaid will bankrupt your company.": "不支付这笔租金，公司将会破产。",
  "BOSS IS BANKRUPT": "老板破产了",
  "UNPAID RENT: 200 COINS": "拖欠租金：200金币",
  "The landlord has closed your office. Start a new company for a fresh beginning.": "房东关闭了办公室。开办一家新公司，重新出发吧。",
  "START A NEW OFFICE": "新建办公室",
  "DESK IN SHOP": "工位已上架",
  "SET IN SHOP": "会议套装已上架",
  "YOUR FIRST CLIENT MEETING": "首次客户会议",
  "FOUNDING TEAM PHOTO UNLOCKED": "创始团队合影已解锁",
  "Your left office is open. After level 30, buy a second team desk and hire your next colleague.": "左侧办公室已开放。通关第30关后，可购买第二个工位并招聘新同事。",
  "Your meeting room is open. After level 50, the meeting set arrives in the shop.": "会议室已开放。通关第50关后，商店将上架会议套装。",
  "The office is open. Your first chapter is complete.": "办公室正式开业。第一章已完成。",
  "The sign is up. Time for your first task.": "招牌挂好了。开始第一项任务吧。",
  "Welcome aboard! Your new colleague is here.": "欢迎加入！新同事来报到了。",
  "Enter a name for your office.": "请输入办公室名称。",
  "Could not save. Check folder access.": "保存失败，请检查文件夹权限。",
  "Could not save. Device storage is unavailable.": "保存失败，设备存储不可用。",
  "Today's gift is already yours.": "今天的礼物已领取。",
  "One free coffee! +3 moves on a level.": "免费咖啡一杯！可为关卡增加3步。",
  "Try the two marked items first.": "请先交换两个标记物品。",
  "Try your new envelope first.": "请先试用新信封。",
  "Tap the envelope first.": "请先点击信封。",
  "Tap the envelope before using a booster.": "使用道具前，请先点击信封。",
  "No match. That move is on us.": "未形成消除，本次不扣步数。",
  "A fresh layout. No move spent.": "已重新排列，不扣步数。",
  "Keep this board. No shuffle used.": "保留当前棋盘，未消耗洗牌道具。",
  "Fresh paperwork. The board was shuffled.": "文件焕然一新！棋盘已洗牌。",
  "Check the word and try again.": "请检查词语，再试一次。",
  "PRINTERS": "打印机",
  "COFFEE": "咖啡",
  "DISCS": "光盘",
  "REPORTS": "报告",
  "MAIL": "信封",
  "NOTES": "便签",
  "STACKS": "文件叠",
  "STAMPS": "印章",
  "BOXES": "箱子",
  "DELIVER": "U盘",
  "CALENDARS": "日历",
  "ITEMS": "物品",
  "FIRST REPORT": "首份报告",
  "PAPERWORK": "文书工作",
  "FIRST ORDERS": "首批订单",
  "MORNING MAIL": "早间邮件",
  "COPY ROOM": "复印室",
  "COFFEE BREAK": "咖啡时间",
  "BUSY DESK": "忙碌的办公桌",
  "FILING DAY": "归档日",
  "FRIDAY LIST": "周五清单",
  "STICKY NOTES": "便利贴",
  "DESK NOTES": "桌上便签",
  "MEETING PREP": "会议准备",
  "SUPPLY RUN": "补充用品",
  "STACK THE FILES": "整理文件",
  "FOLDER FRIDAY": "周五文件夹",
  "DESK ARCHIVE": "桌面档案",
  "NEAT STACKS": "整齐的文件叠",
  "STAMP DUTY": "盖章任务",
  "APPROVAL QUEUE": "等待审批",
  "FINAL COPIES": "最终副本",
  "OUTGOING MAIL": "待发邮件",
  "ARCHIVE DAY": "档案日",
  "USB DELIVERY": "U盘投递",
  "MEETING CALENDARS": "会议日历",
  "LATE DELIVERY": "迟来的投递",
  "LABEL MAKER": "标签整理",
  "KEEP THE AISLE CLEAR": "保持通道畅通",
  "BOTTOM DRAWER": "底层抽屉",
  "STOCK CHECK": "库存盘点",
  "COFFEE AND COPIES": "咖啡与复印件",
  "ARCHIVE FRIDAY": "周五归档",
  "PRIORITY FILES": "优先文件",
  "READY TO SEND": "准备发送",
  "SEND FILES": "发送文件",
  "ONE MORE ATTACHMENT": "再添一个附件",
  "DESK TO DESK": "工位之间",
  "OUTBOX ROUTE": "发件路线",
  "LARGE ATTACHMENT": "大型附件",
  "BACKUP COPY": "备份副本",
  "PAPER TRAFFIC": "文件流转",
  "ALMOST SENT": "即将发送",
  "FINAL VERSION": "最终版本",
  "OPEN FOR BUSINESS": "正式开业",
  "A new item! Match three sticky notes. Complete every target above the board.": "新物品登场！消除三个便签，完成棋盘上方的所有目标。",
  "Move two loose folders together to make a stack. Match THREE ready stacks to collect them. Boosters can prepare a loose folder too.": "将两个散装文件夹合成一叠，再消除三叠文件。道具也能把散装文件夹整理成叠。",
  "Rubber stamps join the board. Match three stamps and finish the other targets before your moves run out.": "印章加入棋盘！消除三个印章，并在步数耗尽前完成其他目标。",
  "Clear items UNDER the flash drives. Deliver them to the bottom arrows. Boosters clear the path but cannot collect a drive in mid-air.": "消除U盘下方的物品，将U盘送到底部箭头处。道具能清路，但不能直接收取悬空的U盘。",
  "Match three desk calendars to prepare your meetings. Deliver the flash drives and finish the reports for your first client.": "消除三个台历，为会议做准备。为首位客户送达U盘并收集报告。",
  "Archive boxes stay in place. Make TWO matches beside each box to open and collect it. Boosters also remove a layer.": "档案箱固定不动。在每个箱子旁消除两次，即可打开并收集。道具也能去掉一层。",
  "DESK LAMP": "台灯",
  "OFFICE PLANT": "办公绿植",
  "WATER COOLER": "饮水机",
  "FILE CABINET": "文件柜",
  "TASK BOARD": "任务看板",
  "SAND PAINT": "沙色涂料",
  "CHALK PAINT": "粉白涂料",
  "PUTTY PAINT": "灰褐涂料",
  "PINSTRIPE PAPER": "细条纹壁纸",
  "EXPOSED BRICK": "裸砖墙面",
  "HALF-PANEL WALL": "半高护墙板",
  "WALNUT PANELS": "胡桃木墙板",
  "ARCHITECT PANELS": "建筑格栅墙板",
  "SAND FINISH": "沙色地面",
  "CHALK FINISH": "粉白地面",
  "PUTTY FINISH": "灰褐地面",
  "CHECKER TILE": "棋盘格地砖",
  "LONG OAK BOARDS": "长条橡木地板",
  "WOVEN CARPET": "编织地毯",
  "CUT STONE": "切石地面",
  "DESIGN TERRAZZO": "设计款水磨石",
  "WORKPLACE": "工位",
  "WALL CLOCK": "挂钟",
  "COFFEE STATION": "咖啡角",
  "BOOK SHELF": "书架",
  "OFFICE SOFA": "办公沙发",
  "PRESENTATION SCREEN": "投影幕布",
  "DESK TELEPHONE": "办公电话",
  "LARGE PLANT": "大型绿植",
  "WHITEWASHED BRICK": "白刷砖墙",
  "LINEN PAPER": "亚麻壁纸",
  "CORK BAND": "软木饰带",
  "SOFT PLASTER": "柔纹灰泥",
  "ARCHITECT CONCRETE": "清水混凝土",
  "WOODEN SLATS": "木条墙面",
  "GEOMETRIC INLAYS": "几何镶嵌",
  "HERRINGBONE": "人字拼木地板",
  "CARPET TILES": "方块地毯",
  "CERAMIC MOSAIC": "陶瓷马赛克",
  "BASKET PARQUET": "篮编拼花地板",
  "LARGE STONE SLABS": "大块石板",
  "GRAPHITE CARPET": "石墨色地毯",
  "BORDERED STONE": "镶边石材",
  "SECOND TEAM DESK": "第二个团队工位",
  "MEETING SET": "会议套装",
  "FOUNDING TEAM": "创始团队合影",
  "A little light. A big start.": "一盏小灯，照亮大计划。",
  "Your quiet green colleague.": "安静的绿色同事。",
  "Where good ideas refill.": "补充水分，也补充灵感。",
  "A home for every report.": "让每份报告都有归处。",
  "Big plans. Small notes.": "小便签，大计划。",
  "A warm, quiet blank canvas.": "温暖宁静，任你发挥。",
  "Soft light. Nothing extra.": "柔和明亮，简单纯粹。",
  "A calm gray-taupe finish.": "沉静的灰褐色调。",
  "A little executive polish.": "添一点老板的气派。",
  "Old brick. A fresh start.": "旧砖墙，新起点。",
  "Paint above. Panels below.": "上涂漆，下铺板。",
  "Warm panels, clean lines.": "温润木板，利落线条。",
  "A carefully framed finish.": "每处细节都恰到好处。",
  "A simple matte surface.": "简洁的哑光表面。",
  "A light, open working space.": "明亮开阔的工作空间。",
  "Quiet color under your feet.": "脚下的一抹宁静。",
  "An old-office classic.": "老办公室的经典风格。",
  "Long boards, a warmer room.": "长条木板，让房间更温暖。",
  "Soft steps. Fewer echoes.": "脚步轻些，回声少些。",
  "A solid foundation for ideas.": "为灵感打下坚实基础。",
  "Small stones. Big statement.": "小石子，大格调。",
  "A compact desk, chair and PC.": "紧凑的桌椅与电脑。",
  "A permanent place in your office.": "办公室里固定的一角。",
  "A quiet finish for a growing office.": "为不断成长的办公室添份沉静。",
  "+50 on first wins.": "首次通关额外获得50金币。",
  "A table and four chairs.": "一张桌子，四把椅子。",
  "Your first chapter, together.": "一起写下团队的第一章。",
  "RESUME": "继续",
  "TYPE THE WORD": "输入词语",
  "Back": "返回",
  "Choose first boss": "选择第一位老板",
  "Choose second boss": "选择第二位老板"
}
;
